# Generated by Django 5.2 on 2026-03-14 11:13

import django.db.models.deletion
import django.utils.timezone
import visitor_access.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("community_core", "0004_neighborhood_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitor_name", models.CharField(max_length=50, verbose_name="访客姓名")),
                (
                    "visitor_phone",
                    models.CharField(blank=True, max_length=30, verbose_name="访客电话"),
                ),
                (
                    "id_number",
                    models.CharField(blank=True, max_length=50, verbose_name="访客证件号"),
                ),
                (
                    "purpose",
                    models.CharField(blank=True, max_length=200, verbose_name="来访事由"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="有效期起"
                    ),
                ),
                ("valid_until", models.DateTimeField(verbose_name="有效期止")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "有效"),
                            ("cancelled", "已取消"),
                            ("expired", "已过期"),
                            ("used", "已使用"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=visitor_access.models.default_token,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="邀请码/令牌",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="实际到访时间"),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitor_invites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="邀请人",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitor_invites",
                        to="community_core.room",
                        verbose_name="到访房间",
                    ),
                ),
            ],
            options={
                "verbose_name": "访客邀请",
                "verbose_name_plural": "访客邀请",
                "ordering": ("-created_at",),
            },
        ),
    ]
