# Generated by Django 6.0.3 on 2026-03-24 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="摄像头名称")),
                (
                    "camera_type",
                    models.CharField(
                        choices=[
                            ("rtsp", "RTSP流"),
                            ("http", "HTTP API"),
                            ("file", "文件"),
                        ],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                ("url", models.CharField(max_length=500, verbose_name="地址")),
                (
                    "location_remark",
                    models.CharField(blank=True, max_length=200, verbose_name="位置备注"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "capture_interval",
                    models.IntegerField(default=300, verbose_name="采集间隔(秒)"),
                ),
                (
                    "last_capture_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后采集时间"),
                ),
                (
                    "last_capture_status",
                    models.CharField(blank=True, max_length=50, verbose_name="采集状态"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "摄像头配置",
                "verbose_name_plural": "摄像头配置",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DetectionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任务名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待检测"),
                            ("processing", "检测中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        default="yolo26n", max_length=50, verbose_name="模型版本"
                    ),
                ),
                ("total_images", models.IntegerField(default=0, verbose_name="总图片数")),
                (
                    "processed_images",
                    models.IntegerField(default=0, verbose_name="已处理"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_detection_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测任务",
                "verbose_name_plural": "检测任务",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FacilityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="facility_images/raw/%Y/%m/", verbose_name="图片"
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="采集时间"),
                ),
                (
                    "location_remark",
                    models.CharField(blank=True, max_length=200, verbose_name="位置备注"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual_upload", "手动上传"),
                            ("camera_capture", "摄像头采集"),
                            ("inspection", "巡检采集"),
                        ],
                        default="manual_upload",
                        max_length=20,
                        verbose_name="图片来源",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_facility_images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传人",
                    ),
                ),
            ],
            options={
                "verbose_name": "设施图片",
                "verbose_name_plural": "设施图片",
                "ordering": ("-captured_at",),
            },
        ),
        migrations.CreateModel(
            name="TrainingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="facility_images/annotated/%Y/%m/", verbose_name="图片"
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        default=dict,
                        help_text='YOLO格式: {"class_id": 0, "bbox": [x_center, y_center, width, height]}',
                        verbose_name="标注数据",
                    ),
                ),
                (
                    "annotation_status",
                    models.CharField(
                        choices=[
                            ("pending", "待标注"),
                            ("annotated", "已标注"),
                            ("verified", "已验证"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="标注状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "annotated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annotated_training_images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="标注人",
                    ),
                ),
                (
                    "original_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_images",
                        to="facility_mgmt.facilityimage",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_training_images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "训练图片",
                "verbose_name_plural": "训练图片",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任务名称")),
                (
                    "dataset_version",
                    models.CharField(max_length=50, verbose_name="数据集版本"),
                ),
                (
                    "base_model",
                    models.CharField(
                        default="yolo26n", max_length=50, verbose_name="基础模型"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待训练"),
                            ("training", "训练中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("epochs", models.IntegerField(default=100, verbose_name="训练轮数")),
                ("batch_size", models.IntegerField(default=16, verbose_name="批次大小")),
                ("image_size", models.IntegerField(default=640, verbose_name="图像尺寸")),
                (
                    "map50",
                    models.FloatField(blank=True, null=True, verbose_name="mAP50"),
                ),
                (
                    "map50_95",
                    models.FloatField(blank=True, null=True, verbose_name="mAP50-95"),
                ),
                (
                    "model_path",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="模型路径"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_training_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "训练任务",
                "verbose_name_plural": "训练任务",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DetectionJobImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="顺序")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_images",
                        to="facility_mgmt.detectionjob",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_associations",
                        to="facility_mgmt.facilityimage",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("job", "image")},
            },
        ),
        migrations.CreateModel(
            name="FacilityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="报告日期")),
                (
                    "total_facilities_detected",
                    models.IntegerField(default=0, verbose_name="检测设施总数"),
                ),
                ("total_damaged", models.IntegerField(default=0, verbose_name="损坏设施数")),
                (
                    "damage_by_category",
                    models.JSONField(default=dict, verbose_name="各类损坏数量"),
                ),
                (
                    "avg_estimated_lifespan_days",
                    models.FloatField(blank=True, null=True, verbose_name="平均剩余寿命(天)"),
                ),
                ("recommendations", models.TextField(blank=True, verbose_name="维护建议")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_facility_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="生成人",
                    ),
                ),
            ],
            options={
                "verbose_name": "设施报告",
                "verbose_name_plural": "设施报告",
                "ordering": ("-report_date",),
                "unique_together": {("report_date",)},
            },
        ),
        migrations.CreateModel(
            name="InferenceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility_category",
                    models.CharField(
                        choices=[
                            ("public_seat", "公共座椅"),
                            ("lighting", "照明灯"),
                            ("electricity_meter", "电表"),
                            ("water_meter", "水表"),
                            ("street_light", "路灯"),
                            ("speed_bump", "减速带"),
                        ],
                        max_length=30,
                        verbose_name="设施类别",
                    ),
                ),
                (
                    "bbox_x1",
                    models.FloatField(help_text="归一化坐标 0-1", verbose_name="边界框X1"),
                ),
                ("bbox_y1", models.FloatField(verbose_name="边界框Y1")),
                ("bbox_x2", models.FloatField(verbose_name="边界框X2")),
                ("bbox_y2", models.FloatField(verbose_name="边界框Y2")),
                (
                    "confidence",
                    models.FloatField(help_text="0-1", verbose_name="检测置信度"),
                ),
                (
                    "damage_level",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("minor", "轻微损坏"),
                            ("moderate", "中等损坏"),
                            ("severe", "严重损坏"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="损坏等级",
                    ),
                ),
                (
                    "damage_confidence",
                    models.FloatField(blank=True, null=True, verbose_name="损坏置信度"),
                ),
                (
                    "estimated_lifespan_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="预计剩余寿命(天)"
                    ),
                ),
                (
                    "lifespan_confidence",
                    models.FloatField(blank=True, null=True, verbose_name="寿命置信度"),
                ),
                (
                    "damage_reasons",
                    models.JSONField(blank=True, default=list, verbose_name="损坏原因列表"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="处理时间"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_results",
                        to="facility_mgmt.facilityimage",
                        verbose_name="图片",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="facility_mgmt.detectionjob",
                        verbose_name="检测任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测结果",
                "verbose_name_plural": "检测结果",
                "ordering": ("-processed_at",),
                "indexes": [
                    models.Index(
                        fields=["image", "facility_category"],
                        name="facility_mg_image_i_5eae9d_idx",
                    ),
                    models.Index(
                        fields=["damage_level"], name="facility_mg_damage__a1b8da_idx"
                    ),
                ],
            },
        ),
    ]
