# Generated by Django 6.0.3 on 2026-03-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameraconfig",
            name="camera_type",
            field=models.CharField(
                choices=[
                    ("rtsp", "RTSP流"),
                    ("http", "HTTP API"),
                    ("usb", "USB摄像头"),
                    ("file", "文件"),
                ],
                max_length=20,
                verbose_name="类型",
            ),
        ),
    ]
