# Generated by Django 5.2 on 2026-03-19 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_login_audit_systemconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseholdComfortSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temp_min",
                    models.DecimalField(
                        decimal_places=1,
                        default=18.0,
                        max_digits=4,
                        verbose_name="温度下限（摄氏度）",
                    ),
                ),
                (
                    "temp_max",
                    models.DecimalField(
                        decimal_places=1,
                        default=28.0,
                        max_digits=4,
                        verbose_name="温度上限（摄氏度）",
                    ),
                ),
                (
                    "humidity_min",
                    models.DecimalField(
                        decimal_places=1,
                        default=40.0,
                        max_digits=4,
                        verbose_name="湿度下限（%RH）",
                    ),
                ),
                (
                    "humidity_max",
                    models.DecimalField(
                        decimal_places=1,
                        default=70.0,
                        max_digits=4,
                        verbose_name="湿度上限（%RH）",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_comfort_setting",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="户主用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "户主舒适范围",
                "verbose_name_plural": "户主舒适范围",
            },
        ),
    ]
