# Generated by Django 5.2 on 2026-03-14 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("community_core", "0004_neighborhood_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="费用名称")),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, verbose_name="编号"),
                ),
                (
                    "unit",
                    models.CharField(
                        default="元",
                        help_text="如：元/月、元/度",
                        max_length=30,
                        verbose_name="单位",
                    ),
                ),
            ],
            options={
                "verbose_name": "费用类型",
                "verbose_name_plural": "费用类型",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        help_text="如：2024-01 表示 2024年1月",
                        max_length=20,
                        verbose_name="账期",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="应收金额"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="已缴金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待缴费"),
                            ("partial", "部分缴费"),
                            ("paid", "已缴清"),
                            ("overdue", "已逾期"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="到期日"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="缴清时间"),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="community_core.room",
                        verbose_name="房间",
                    ),
                ),
                (
                    "fee_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="property_fees.feetype",
                        verbose_name="费用类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "账单",
                "verbose_name_plural": "账单",
                "ordering": ("-period", "-created_at"),
                "unique_together": {("room", "fee_type", "period")},
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="缴费金额"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("offline", "线下/现金"),
                            ("bank", "银行转账"),
                            ("online", "在线缴费"),
                            ("other", "其他"),
                        ],
                        default="offline",
                        max_length=20,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="缴费时间"),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="property_fees.bill",
                        verbose_name="账单",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_payments_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "缴费记录",
                "verbose_name_plural": "缴费记录",
                "ordering": ("-paid_at",),
            },
        ),
    ]
