# Generated by Django 5.2 on 2026-03-14 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="车位编号"),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True,
                        help_text="如：地库A区、地面B区",
                        max_length=100,
                        verbose_name="区域",
                    ),
                ),
                (
                    "space_type",
                    models.CharField(
                        choices=[("fixed", "固定车位"), ("temp", "临停车位")],
                        default="fixed",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vacant", "空闲"),
                            ("occupied", "占用"),
                            ("reserved", "预留"),
                        ],
                        default="vacant",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "车位",
                "verbose_name_plural": "车位",
                "ordering": ("zone", "code"),
            },
        ),
        migrations.CreateModel(
            name="TempParkingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_number", models.CharField(max_length=20, verbose_name="车牌号")),
                ("start_time", models.DateTimeField(verbose_name="预计进入时间")),
                ("end_time", models.DateTimeField(verbose_name="预计离开时间")),
                (
                    "purpose",
                    models.CharField(blank=True, max_length=200, verbose_name="事由"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "admin_remark",
                    models.CharField(blank=True, max_length=200, verbose_name="审批备注"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_parking_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "临停申请",
                "verbose_name_plural": "临停申请",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ViolationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_number", models.CharField(max_length=20, verbose_name="车牌号")),
                (
                    "violation_type",
                    models.CharField(
                        help_text="如：违停、占道", max_length=100, verbose_name="违规类型"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="违规说明"),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发生时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待处理"), ("paid", "已处理")],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="录入时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violation_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联户主",
                    ),
                ),
            ],
            options={
                "verbose_name": "违规记录",
                "verbose_name_plural": "违规记录",
                "ordering": ("-occurred_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_number", models.CharField(max_length=20, verbose_name="车牌号")),
                (
                    "brand_model",
                    models.CharField(blank=True, max_length=100, verbose_name="品牌型号"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=30, verbose_name="颜色"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登记时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="车主",
                    ),
                ),
            ],
            options={
                "verbose_name": "车辆",
                "verbose_name_plural": "车辆",
                "ordering": ("-created_at",),
                "unique_together": {("user", "plate_number")},
            },
        ),
    ]
