# Generated by Django 5.2 on 2026-03-10 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="楼栋名称")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="楼栋编号"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, verbose_name="详细地址"),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "楼栋",
                "verbose_name_plural": "楼栋",
            },
        ),
        migrations.CreateModel(
            name="ResidentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="标签名称"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="说明"),
                ),
            ],
            options={
                "verbose_name": "住户标签",
                "verbose_name_plural": "住户标签",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "floor_no",
                    models.CharField(blank=True, max_length=10, verbose_name="楼层"),
                ),
                ("room_no", models.CharField(max_length=20, verbose_name="房号")),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="建筑面积(㎡)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("occupied", "已入住"),
                            ("vacant", "空置"),
                            ("reserved", "预留"),
                        ],
                        default="vacant",
                        max_length=20,
                        verbose_name="房间状态",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(blank=True, max_length=50, verbose_name="产权人姓名"),
                ),
                (
                    "owner_phone",
                    models.CharField(blank=True, max_length=30, verbose_name="产权人电话"),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="可选，绑定到实际登录账号的户主。",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_rooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="绑定户主账号",
                    ),
                ),
            ],
            options={
                "verbose_name": "房间",
                "verbose_name_plural": "房间",
            },
        ),
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="联系电话"),
                ),
                (
                    "id_number",
                    models.CharField(blank=True, max_length=50, verbose_name="证件号"),
                ),
                (
                    "is_householder",
                    models.BooleanField(default=False, verbose_name="是否户主"),
                ),
                (
                    "relation_to_householder",
                    models.CharField(
                        blank=True,
                        help_text="如：本人、配偶、子女、父母等",
                        max_length=50,
                        verbose_name="与户主关系",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "在住"),
                            ("moved_out", "已迁出"),
                            ("arrears", "欠费"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="住户状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="residents",
                        to="community_core.residenttag",
                        verbose_name="标签",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="residents",
                        to="community_core.room",
                        verbose_name="房间",
                    ),
                ),
            ],
            options={
                "verbose_name": "住户",
                "verbose_name_plural": "住户",
            },
        ),
        migrations.CreateModel(
            name="OwnershipChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_owner_name",
                    models.CharField(blank=True, max_length=50, verbose_name="原产权人姓名"),
                ),
                (
                    "new_owner_name",
                    models.CharField(max_length=50, verbose_name="新产权人姓名"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="变更时间"),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="变更原因"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ownership_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_changes",
                        to="community_core.room",
                        verbose_name="房间",
                    ),
                ),
            ],
            options={
                "verbose_name": "产权变更记录",
                "verbose_name_plural": "产权变更记录",
                "ordering": ("-changed_at",),
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="单元名称/编号")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="community_core.building",
                        verbose_name="楼栋",
                    ),
                ),
            ],
            options={
                "verbose_name": "单元",
                "verbose_name_plural": "单元",
                "unique_together": {("building", "name")},
            },
        ),
        migrations.AddField(
            model_name="room",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="community_core.unit",
                verbose_name="单元",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("unit", "room_no")},
        ),
    ]
