# Generated by Django 5.2 on 2026-03-14 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_core", "0003_announcement_activity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NeighborhoodPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("dynamic", "动态"),
                            ("second_hand", "二手市场"),
                            ("help", "邻里互助"),
                        ],
                        default="dynamic",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="动态可留空，二手/互助建议填写",
                        max_length=200,
                        verbose_name="标题",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "contact_info",
                    models.CharField(
                        blank=True,
                        help_text="选填，二手/互助可留电话或房号",
                        max_length=100,
                        verbose_name="联系方式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("hidden", "已隐藏"),
                            ("violated", "违规下架"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighborhood_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布人",
                    ),
                ),
            ],
            options={
                "verbose_name": "邻里圈帖子",
                "verbose_name_plural": "邻里圈帖子",
                "ordering": ("-created_at",),
            },
        ),
    ]
