# Generated by Django 5.2 on 2026-03-14 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_core", "0004_neighborhood_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LostItemReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_desc", models.CharField(max_length=200, verbose_name="物品描述")),
                (
                    "lost_place",
                    models.CharField(blank=True, max_length=200, verbose_name="丢失地点"),
                ),
                (
                    "lost_time",
                    models.CharField(blank=True, max_length=200, verbose_name="丢失时间说明"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=30, verbose_name="联系电话"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="补充说明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("found", "已找到"),
                            ("closed", "已关闭"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_item_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="报失人",
                    ),
                ),
            ],
            options={
                "verbose_name": "物品报失",
                "verbose_name_plural": "物品报失",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ParcelRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrier",
                    models.CharField(blank=True, max_length=50, verbose_name="快递公司"),
                ),
                (
                    "pickup_code",
                    models.CharField(blank=True, max_length=50, verbose_name="取件码"),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待取"), ("taken", "已取")],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登记时间"),
                ),
                (
                    "taken_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="取件时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcel_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="登记人",
                    ),
                ),
            ],
            options={
                "verbose_name": "快递代收",
                "verbose_name_plural": "快递代收",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ServiceBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        help_text="如：保洁、维修、搬家", max_length=50, verbose_name="服务类型"
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(blank=True, null=True, verbose_name="期望日期"),
                ),
                (
                    "preferred_time",
                    models.CharField(
                        blank=True,
                        help_text="如：上午、下午",
                        max_length=100,
                        verbose_name="期望时段",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=30, verbose_name="联系电话"),
                ),
                (
                    "address_remark",
                    models.CharField(
                        blank=True,
                        help_text="楼栋房号等",
                        max_length=200,
                        verbose_name="地址备注",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注说明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("confirmed", "已接单"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="预约人",
                    ),
                ),
            ],
            options={
                "verbose_name": "家政预约",
                "verbose_name_plural": "家政预约",
                "ordering": ("-created_at",),
            },
        ),
    ]
